@startuml

[*] --> STARTED
STARTED --> FINISHED
STARTED --> CANCELED
STARTED : this is the initial state
STARTED : when the match start and
STARTED : when it is on going

FINISHED : this is the final status
FINISHED : when the match ends
FINISHED : with a winner

CANCELED : this is the final status
CANCELED : when the match ends
CANCELED : without a winner

FINISHED --> [*]
CANCELED --> [*]
@enduml