@startuml
skinparam componentStyle uml1
skinparam lineType polyline

database "plays_rps"

package "Controllers" {
[PlayController]
}

[PlayController] --(createPlay

package "Services" {
createPlay -- [PlayServices]
}

[PlayServices] --(savePlay

package "Repositories" {
savePlay -- [PlayRepository]
[PlayRepository] --("plays_rps"
}

@enduml